CREATE DATABASE IF NOT EXISTS boleto_baile_db;

CREATE TABLE IF NOT EXISTS boletos ( \
    id SERIAL PRIMARY KEY, \
    app VARCHAR(100) NOT NULL, \
    apm VARCHAR(100) NOT NULL, \ 
    nombre VARCHAR(100) NOT NULL, \
    email VARCHAR(250) NOT NULL, \
    createdat TIMESTAMP NOT NULL DEFAULT NOW() \
);